[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@cryptoalgebra/core/=lib/Algebra/src/core/",
    "@cryptoalgebra/periphery/=lib/Algebra/src/periphery/",
    "@cryptoalgebra/tokenomics/=lib/Algebra/src/tokenomics/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
